# This file was generated by GoReleaser. DO NOT EDIT.
class Bit < Formula
  desc "A modern git CLI"
  homepage "https://github.com/chriswalz/bit"
  version "0.7.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/chriswalz/bit/releases/download/v0.7.4/bit_0.7.4_darwin_amd64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "244267d9ba145eaf8c0f25d3198d5d77772498d9b583603ec29f0974526c92a3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/chriswalz/bit/releases/download/v0.7.4/bit_0.7.4_linux_amd64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "62fa06ce4de46e3d3d6e9a92015697cc5fce9058506977c3fdfed108cf9ce03e"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chriswalz/bit/releases/download/v0.7.4/bit_0.7.4_linux_arm64.tar.gz", :using => CurlDownloadStrategy.
        sha256 "92cf424828433b1f96cf57bfc5ef1ee36b2ee8e4a8243b436937e7125150e532"
      else
      end
    end
  end

  def install
    bin.install "bit"
  end

  test do
    system "#{bin}/program --version"
    ...
  end
end
